FROM php:7.4-fpm

RUN apt-get update && apt-get install -y \
    build-essential \
    libpng-dev \
    libjpeg62-turbo-dev \
    libfreetype6-dev \
    libonig-dev \
    locales \
    zip \
    jpegoptim optipng pngquant gifsicle \
    vim \
    unzip \
    git \
    curl \
    libzip-dev \
    nodejs \
    npm \
    libpq-dev

RUN apt-get clean && rm -rf /var/lib/apt/lists/*

RUN docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql
RUN docker-php-ext-install pdo_mysql mbstring zip exif pcntl pgsql pdo_pgsql bcmath mysqli
RUN docker-php-ext-configure gd --with-freetype=/usr/include/ --with-jpeg=/usr/include/
RUN docker-php-ext-install -j$(nproc) gd

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN pecl install xdebug-3.1.5 \
    && docker-php-ext-enable xdebug

RUN apt-get update
RUN apt-get install -y locales locales-all
ENV LC_ALL nl_NL.utf8
ENV LANG nl_NL.utf8
ENV LANGUAGE nl_NL.utf8

EXPOSE 9000
CMD ["php-fpm"]

ARG USER_ID
ARG GROUP_ID

RUN addgroup --gid 1000 user
RUN adduser --disabled-password --gecos '' --uid 1000 --gid 33 user
USER user