services:
  nginx:
    build: ./docker/nginx
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
      - ./app:/var/www/html
      - ./docker/nginx/logs/:/var/log/nginx
    networks:
      - internal

  php:
    build: ./docker/php
    container_name: php
    restart: always
    ports:
      - 5173:5173
    volumes:
      - ./app:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini:cached
      - ./docker/php/composer/:/root/.composer:cached
    networks:
      - internal

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Europe/Amsterdam
    networks:
      - internal

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    restart: always
    ports:
      - 1025:1025
      - 8025:8025

networks:
  internal:
    driver: bridge

